name: samloader build

on:
  workflow_dispatch:

jobs:
  linux-x64:
    name: Build for Linux (x64)
    runs-on: ubuntu-24.04

    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build samloader
        run: |
          # Install packages
          sudo apt-get update
          sudo apt-get -y install musl-tools
          rustup update
          rustup target add x86_64-unknown-linux-musl

          # Get linux headers since musl does not include them
          git clone https://github.com/sabotage-linux/kernel-headers.git
          cd kernel-headers
          make ARCH=x86_64 prefix=../linux-usr install
          cd ../
          export CFLAGS_x86_64_unknown_linux_musl="-I $(readlink -f linux-usr/include)"

          # Build samloader
          cargo build -p samloader --target x86_64-unknown-linux-musl --release
          tar c -C target/x86_64-unknown-linux-musl/release samloader | \
            xz --x86 --lzma2 > samloader-linux-x86_64.tar.xz

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: samloader-*.tar.xz
          archive: false

  linux-arm64:
    name: Build for Linux (arm64)
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build samloader
        run: |
          # Install packages
          sudo apt-get update
          sudo apt-get -y install musl-tools
          rustup update
          rustup target add aarch64-unknown-linux-musl

          # Get linux headers since musl does not include them
          git clone https://github.com/sabotage-linux/kernel-headers.git
          cd kernel-headers
          make ARCH=arm64 prefix=../linux-usr install
          cd ../
          export CFLAGS_aarch64_unknown_linux_musl="-I $(readlink -f linux-usr/include)"

          # Build samloader
          cargo build -p samloader --target aarch64-unknown-linux-musl --release
          tar c -C target/aarch64-unknown-linux-musl/release samloader | \
            xz --x86 --lzma2 > samloader-linux-arm64.tar.xz

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: samloader-*.tar.xz
          archive: false

  windows-x64:
    name: Build for Windows (x64)
    runs-on: windows-2025
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build samloader
        run: |
          rustup update
          cargo build -p samloader --release
          tar c -C target/release samloader.exe | \
            xz --x86 --lzma2 > samloader-windows-x86_64.tar.xz

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: samloader-*.tar.xz
          archive: false

  windows-arm64:
    name: Build for Windows (arm64)
    runs-on: windows-11-arm
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build samloader
        run: |
          rustup update
          cargo build -p samloader --release
          tar c -C target/release samloader.exe | \
            xz --x86 --lzma2 > samloader-windows-arm64.tar.xz

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: samloader-*.tar.xz
          archive: false

  macos:
    name: Build for macOS
    runs-on: macos-26

    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Build samloader
        run: |
          rustup update
          rustup target add x86_64-apple-darwin
          cargo build -p samloader --target aarch64-apple-darwin --release
          cargo build -p samloader --target x86_64-apple-darwin --release
          lipo -create -output target/samloader \
            target/aarch64-apple-darwin/release/samloader \
            target/x86_64-apple-darwin/release/samloader
          codesign -s - target/samloader
          tar c -C target samloader | xz --x86 --lzma2 > samloader-macos-universal.tar.xz

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: samloader-*.tar.xz
          archive: false
